### ISSUE TITLE
The 'plug in' requires Visual Studio 2015

### ISSUE THREAD

**Issue by cauivy** [Azure-Samples/academic-knowledge-analytics-visualization#1]
Hello, guys!

I  followed the instruction get Visual Studio 2017 and Plug in for Visual Studio 2015 downloaded. When I tried to install the plug in, I was told that 'The pluginvrequires Visual Studio 2015'.  Should I download Visual Studio 2015 instead 2017?

Thanks in advance!

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alch-msft** [comment]
Hello, 
  If you have visual studio 2017, the plugin should already be installed. If you have visual studio 2015, you'll need to download and install the plugin separately.
