### ISSUE TITLE
PaperAuthorAffiliations from CreateDatabase.usql fails with never MAG versions

### ISSUE THREAD

**Issue by andreas-wilm** [Azure-Samples/academic-knowledge-analytics-visualization#3]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Run `CreateDatabase.usql` from `00. Common Scripts` with recent MAG versions

The code that's used to create the `PaperAuthorAffiliations` table is responsible and sufficient to trigger the error described below.

### Any log messages given by the failure

```
Vertex failed
Vertex SV25_Extract_Partition[38]
VertexFailedFast: Vertex failed with a fail-fast error
E_RUNTIME_USER_EXTRACT_ROW_DELIMITER_EXPECTED: Too many columns in input record.

Description
Expected row delimiter in input record after processing 1 record(s) in the vertex' input split. Expected 5 column(s) but encountered more data.

Row Delimiter: 0x0
Column Delimiter: 0x9
HEX: 52 C3 B8 79 09 0D 0A 32 39 31 37 34 33 30 31 36 39 09 32 39 31 36 39 39 30 39 35 34 09 09 36 09 43 2E 20 53 63 68 6F 6C 7A 65 09 ### 0D 0A 32 39 31 37 34 33 30 31 37 30 09 32 31 31 30 32 31 33 34 36 34 09 31 37 33
TEXT: R..y\t\r\n2917430169\t2916990954\t\t6\tC. Scholze\t ### \r\n2917430170\t2110213464\t173
```

I managed to narrow it down to the PaperAuthorAffiliations table creation. All other tables are created fine. The oldest MAG version I have access to works (2019-03-11), all others fail. See below

### Expected/desired behavior

Successful completion on all MAG versions

### OS and Version?

Azure Portal

### Versions

- mag-2019-04-11: Fails
- mag-2019-04-01: Fails
- mag-2019-03-22: Fails
- mag-2019-03-11: Works

### Mention any other details that might be useful

NA

**Comment by andreas-wilm** [comment]
Just to add on: running the full script on mag-2019-03-11 fails also eventually. Not sure where. The error is

```
Failure when attempting to convert empty column data.

Description
Can not convert EMPTY string to proper type.
Details
Row Delimiter: 0x0
Column Delimiter: 0x9
HEX: 75 72 6F 70 65 20 6E 75 74 73 20 31 20 64 65 6D 6F 67 72 61 70 68 69 63 73 09 32 30 31 30 20 45 75 72 6F 70 65 20 4E 55 54 53 20 31 20 44 65 6D 6F 67 72 61 70 68 69 63 73 09 09 09 ### 09 09 09 09 09 09 09 09 09 30
TEXT: urope nuts 1 demographics\t2010 Europe NUTS 1 Demographics\t\t\t ### \t\t\t\t\t\t\t\t\t0
```

**Comment by andreas-wilm** [comment]
Turns out this was a problem of using the latest code from here (most recent), with different, incompatible deployed MAG versions. Hattip to Charles Huang. 

The dependency wasn't clear from the website. It might help to explicitely mention here, that you have to use the script from the corresponding deployment and not from here/github. 

Another improvement would be to have versioned release of this repo that are pegged to MAG release versions. 

Anyway, problem solved for me

**Comment by oersted** [comment]
@andreas-wilm I seem to be having the same problem with the most recent version (mag-2019-06-27). I have made sure I am using the latest U-SQL code from `mag-2019-06-27/samples`. In my case, I run `CreateFunctions.usql` which succeeds, and then running any job which reads `Papers.txt` or `PaperAuthorAffiliations.txt` I get similar errors, but this time not at the very beginning, but after successfully reading several GB of the tables.

Example from `Papers.txt`,

```
E_RUNTIME_USER_EXTRACT_ROW_DELIMITER_EXPECTED: Too many columns in input record.

Expected row delimiter in input record after processing 813729 record(s) in the vertex' input split. Expected 23 column(s) but encountered more data.

Row Delimiter: 0xA
Column Delimiter: 0x9
HEX: 6E 73 09 09 32 30 31 30 09 32 30 31 30 2D 30 36 2D 30 38 09 57 49 4C 45 59 E2 80 90 56 43 48 20 56 65 72 6C 61 67 09 34 31 33 35 34 30 36 34 09 09 09 33 31 09 31 39 09 09 09 31 09 ### 32 09 33 09 43 68 65 6D 49 6E
TEXT: ns\t\t2010\t2010-06-08\tWILEY...VCH Verlag\t41354064\t\t\t31\t19\t\t\t1\t ### 2\t3\tChemIn
```

Example from `PaperAuthorAffiliations.txt`,

```
E_RUNTIME_USER_EXTRACT_ROW_DELIMITER_EXPECTED: Too many columns in input record.

Expected row delimiter in input record after processing 3547852 record(s) in the vertex' input split. Expected 6 column(s) but encountered more data.

Row Delimiter: 0xA
Column Delimiter: 0x9
HEX: 39 09 ### 32 36 33 32 39 34 32 35 34 33 09 09 31 09 56 69 63 74 6F 72 69 61 6E 6F 20 50 65 72 72 75 63 61 20 41 6C 62 61 64 61 6C 65 6A 6F 09 0D 0A 31 35 09 31 39 39 31 34 32 34 39 37 09 09 31 09 52 6F 62 65 72 74
TEXT: 9\t ### 2632942543\t\t1\tVictoriano Perruca Albadalejo\t\r\n15\t199142497\t\t1\tRobert
```

I have a suspicion that this is happening because a field that is not declared as optional is null. This must be rare, as it happens after successfully reading millions of records from the same table. I'll keep experimenting and I'll report back if I find a solution.

**Comment by oersted** [comment]
I also keep getting dozens of these errors while running U-SQL jobs on MAG. They don't make much sense, as the Storage Account does exist and Data Lake is indeed able to successfully read from Affiliations.txt for example.

![image](https://user-images.githubusercontent.com/11427574/61629708-fdc9cf00-ac85-11e9-9809-f521b41ed059.png)

This is probably an unrelated issue, I'm not sure if it belongs here.

**Comment by oersted** [comment]
Setting `silent: true` on the extractor prevents the exception at least, for now.

**Comment by andreas-wilm** [comment]
Hey Jon, confirmed. There is an issue. 
MSR are looking into it. 
Andreas

**Comment by cyhuang01** [comment]
This is an Azure Data Lake Analytics issue. Product team is work on it.

**Comment by cyhuang01** [comment]
FYI. Product team has fixed this issue. Please try running your script again.

**Comment by alexgman** [comment]
This issue is not fixed yet.
